name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /tmp/android-sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Gradle
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Cache Android SDK
      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: ${{ env.ANDROID_SDK_ROOT }}
          key: android-sdk-${{ runner.os }}-34
          restore-keys: |
            android-sdk-${{ runner.os }}-

      - name: Install Android command-line tools and SDK packages
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools"
          if [ ! -d "${ANDROID_SDK_ROOT}/cmdline-tools/latest" ]; then
            wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /tmp/cmdline.zip
            unzip -q /tmp/cmdline.zip -d "${ANDROID_SDK_ROOT}/cmdline-tools"
            mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools/latest"
            mv "${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools"/* "${ANDROID_SDK_ROOT}/cmdline-tools/latest/" || true
          fi
          SDKMANAGER="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"
          export PATH="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin:${ANDROID_SDK_ROOT}/platform-tools:${PATH}"
          yes | $SDKMANAGER --sdk_root="${ANDROID_SDK_ROOT}" --licenses
          $SDKMANAGER --sdk_root="${ANDROID_SDK_ROOT}" "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Show built APK files
        run: ls -la app/build/outputs/apk/debug || true

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: float-tools-apk
          path: app/build/outputs/apk/debug/*.apk
