# .github/workflows/build-apk.yml

name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Show built APK files (for debugging)
        run: ls -la app/build/outputs/apk/debug || true

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: float-tools-apk
          path: app/build/outputs/apk/debug/*.apk
